// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-analyses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_analyses_default = defineTool({
  name: "list_analyses",
  title: "List X-ray analyses",
  description: "List chest X-ray analyses (prediction, confidence, findings) belonging to the signed-in MedVision user.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 20)."),
    prediction: z.enum(["Pneumonia", "Normal"]).optional().describe("Optional filter by prediction label.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, prediction }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("analyses").select("id, prediction, confidence, findings, original_filename, model_used, created_at, patient_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (prediction) q = q.eq("prediction", prediction);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { analyses: data ?? [] } };
  }
});

// src/lib/mcp/tools/get-analysis.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_analysis_default = defineTool2({
  name: "get_analysis",
  title: "Get X-ray analysis",
  description: "Fetch one chest X-ray analysis by id for the signed-in MedVision user.",
  inputSchema: { id: z2.string().uuid().describe("Analysis UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("analyses").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { analysis: data } };
  }
});

// src/lib/mcp/tools/list-patients.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool3({
  name: "list_patients",
  title: "List patients",
  description: "List patient records the signed-in MedVision user has access to.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum rows to return (default 50)."),
    search: z3.string().optional().describe("Case-insensitive substring match on patient_name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("patients").select("id, patient_name, age, gender, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) q = q.ilike("patient_name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { patients: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-patient.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_patient_default = defineTool4({
  name: "create_patient",
  title: "Create patient",
  description: "Create a new patient record for the signed-in MedVision user.",
  inputSchema: {
    patient_name: z4.string().min(1).describe("Patient full name."),
    age: z4.number().int().min(0).max(150).optional(),
    gender: z4.string().optional(),
    notes: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("patients").insert({ ...input, created_by: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { patient: data } };
  }
});

// src/lib/mcp/tools/list-diseases.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_diseases_default = defineTool5({
  name: "list_diseases",
  title: "List diseases",
  description: "List the diseases catalog configured in the MedVision admin portal.",
  inputSchema: {
    only_active: z5.boolean().optional().describe("If true, return only active diseases (default true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser5(ctx).from("diseases").select("id, name, description, severity, is_active").order("name");
    if (only_active !== false) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { diseases: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bnsjakzmwoluhbxybhwl";
var mcp_default = defineMcp({
  name: "medvision-mcp",
  title: "MedVision MCP",
  version: "0.1.0",
  instructions: "Tools for MedVision, an AI chest X-ray pneumonia diagnostic app. Use list_analyses/get_analysis to review the signed-in user's X-ray results, list_patients/create_patient to manage their patient records, and list_diseases to browse the diseases catalog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analyses_default, get_analysis_default, list_patients_default, create_patient_default, list_diseases_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
